import Foundation

struct ZshShellIntegrationInstallation: Equatable {
    let environment: [String: String]
    let wrapperDirectory: URL
}

enum ZshShellIntegration {
    private static let version = 3
    private static let startupFiles = [".zshenv", ".zprofile", ".zshrc", ".zlogin", ".zlogout"]

    /// Installs a tiny ZDOTDIR proxy owned by Ourocode. Every real user startup
    /// file is sourced exactly once with the user's own ZDOTDIR visible. The
    /// integration registers from `.zshenv`, before prompt themes run, but
    /// defers its hook installation until the first `precmd`. The account shell
    /// is still the original `zsh -l -i`; there is no nested shell or
    /// replacement rc.
    static func install(
        inherited: [String: String],
        homeDirectory: URL,
        applicationSupportDirectory: URL
    ) throws -> ZshShellIntegrationInstallation {
        let originalZDOTDIR = normalizedUserZDOTDIR(
            inherited["ZDOTDIR"],
            homeDirectory: homeDirectory
        )
        let wrapper = applicationSupportDirectory
            .appendingPathComponent("Ourocode", isDirectory: true)
            .appendingPathComponent("zsh-integration-v\(version)", isDirectory: true)
        try FileManager.default.createDirectory(
            at: wrapper,
            withIntermediateDirectories: true
        )

        for filename in startupFiles {
            let content = proxySource(filename: filename)
                + (filename == ".zshenv" ? conversationHooks : "")
            try writeIfChanged(Data(content.utf8), to: wrapper.appendingPathComponent(filename))
        }

        var environment = inherited
        environment["OUROCODE_ORIGINAL_ZDOTDIR"] = originalZDOTDIR.path
        environment["OUROCODE_INTEGRATION_ZDOTDIR"] = wrapper.path
        environment["OUROCODE_SHELL_INTEGRATION"] = "osc133-osc7-v3"
        environment["ZDOTDIR"] = wrapper.path
        return ZshShellIntegrationInstallation(
            environment: environment,
            wrapperDirectory: wrapper
        )
    }

    private static func normalizedUserZDOTDIR(
        _ configured: String?,
        homeDirectory: URL
    ) -> URL {
        guard let configured, !configured.isEmpty else {
            return homeDirectory.standardizedFileURL
        }
        let expanded = (configured as NSString).expandingTildeInPath
        if expanded.hasPrefix("/") {
            return URL(fileURLWithPath: expanded, isDirectory: true).standardizedFileURL
        }
        return homeDirectory.appendingPathComponent(expanded, isDirectory: true).standardizedFileURL
    }

    private static func proxySource(filename: String) -> String {
        """
        # Generated by Ourocode. User startup files remain authoritative.
        typeset _ourocode_wrapper_zdotdir="${OUROCODE_INTEGRATION_ZDOTDIR}"
        typeset _ourocode_user_zdotdir="${OUROCODE_USER_ZDOTDIR:-${OUROCODE_ORIGINAL_ZDOTDIR}}"
        if [[ -n "$_ourocode_user_zdotdir" && -r "$_ourocode_user_zdotdir/\(filename)" ]]; then
          ZDOTDIR="$_ourocode_user_zdotdir"
          builtin source "$_ourocode_user_zdotdir/\(filename)"
          if [[ -n "${ZDOTDIR:-}" && "$ZDOTDIR" != "$_ourocode_user_zdotdir" ]]; then
            typeset -gx OUROCODE_USER_ZDOTDIR="$ZDOTDIR"
          else
            typeset -gx OUROCODE_USER_ZDOTDIR="$_ourocode_user_zdotdir"
          fi
        fi
        typeset -gx ZDOTDIR="$_ourocode_wrapper_zdotdir"
        unset _ourocode_wrapper_zdotdir _ourocode_user_zdotdir

        """
    }

    private static let conversationHooks = #"""
    if [[ -o interactive && -z "${OUROCODE_OSC133_ACTIVE:-}" ]]; then
      typeset -gx OUROCODE_OSC133_ACTIVE=1
      typeset -gi _OUROCODE_OSC133_STATE=0
      typeset -gi _OUROCODE_TTY_FD=1

      # Powerlevel10k redirects stdout and stderr while its instant prompt is
      # active. Semantic terminal control must bypass that capture. zsh/system
      # is the only zsh API that can open /dev/tty with O_CLOEXEC, so the
      # descriptor neither collides with user FDs nor leaks to child commands.
      {
        builtin zmodload zsh/system && (( $+builtins[sysopen] )) && {
          { [[ -n "${TTY:-}" && -w "$TTY" ]] && builtin sysopen -o cloexec -wu _OUROCODE_TTY_FD -- "$TTY" } ||
          { [[ -w /dev/tty ]] && builtin sysopen -o cloexec -wu _OUROCODE_TTY_FD -- /dev/tty }
        }
      } 2>/dev/null || (( _OUROCODE_TTY_FD = 1 ))

      _ourocode_deferred_init() {
        builtin emulate -L zsh -o no_aliases -o no_warn_create_global

        _ourocode_precmd() {
          builtin local -i _ourocode_status=$?
          builtin emulate -L zsh -o no_aliases -o no_warn_create_global

          # Plugins may invoke precmd from inside ZLE to redraw a prompt. OSC
          # output there would land in the user's edit buffer, so only annotate
          # the real prompt boundary.
          if ! builtin zle; then
            if (( _OUROCODE_OSC133_STATE == 1 )); then
              builtin print -rnu $_OUROCODE_TTY_FD -- $'\e]133;D;'${_ourocode_status}$'\a'
            fi
            _OUROCODE_OSC133_STATE=2

            # OSC 7 is the portable cwd contract consumed by the Ghostty
            # engine. Escape URI delimiters that change URL semantics.
            builtin local _ourocode_pwd_uri="${PWD//\%/%25}"
            _ourocode_pwd_uri="${_ourocode_pwd_uri// /%20}"
            _ourocode_pwd_uri="${_ourocode_pwd_uri//[#]/%23}"
            _ourocode_pwd_uri="${_ourocode_pwd_uri//[?]/%3F}"
            builtin print -rnu $_OUROCODE_TTY_FD -- $'\e]7;file://localhost'"$_ourocode_pwd_uri"$'\a'

            if [[ -n "${_OUROCODE_MARKED_PS1+x}" && "$PS1" == "$_OUROCODE_MARKED_PS1" ]]; then
              PS1="$_OUROCODE_SAVED_PS1"
            fi
            builtin local _ourocode_mark_a=$'%{\e]133;A\a%}'
            builtin local _ourocode_mark_b=$'%{\e]133;B\a%}'
            if [[ -o prompt_percent && "${precmd_functions[-1]:-}" == _ourocode_precmd ]]; then
              typeset -g _OUROCODE_SAVED_PS1="$PS1"
              PS1="${_ourocode_mark_a}${PS1}${_ourocode_mark_b}"
              typeset -g _OUROCODE_MARKED_PS1="$PS1"
            else
              # Prompt frameworks often insist on the final precmd slot. Move
              # toward that slot for the next prompt and emit A directly for
              # this one; line-init below supplies B if the theme wins again.
              precmd_functions=(${precmd_functions:#_ourocode_precmd} _ourocode_precmd)
              builtin print -rnu $_OUROCODE_TTY_FD -- $'\e]133;A\a'
            fi
          fi
        }

        _ourocode_preexec() {
          builtin emulate -L zsh -o no_aliases -o no_warn_create_global
          if [[ -n "${_OUROCODE_MARKED_PS1+x}" && "$PS1" == "$_OUROCODE_MARKED_PS1" ]]; then
            PS1="$_OUROCODE_SAVED_PS1"
          fi
          builtin print -rnu $_OUROCODE_TTY_FD -- $'\e]133;C\a'
          _OUROCODE_OSC133_STATE=1
        }

        _ourocode_zle_line_init() {
          builtin emulate -L zsh -o no_aliases -o no_warn_create_global
          # ZLE begins after the theme has drawn PS1. Marking input here avoids
          # a one-shot PS1 rewrite that Powerlevel10k can discard, while still
          # giving the terminal the complete A -> B -> C -> D contract.
          if [[ -z "${_OUROCODE_MARKED_PS1+x}" || "$PS1" != "$_OUROCODE_MARKED_PS1" ]]; then
            builtin print -rnu $_OUROCODE_TTY_FD -- $'\e]133;P;k=i\a\e]133;B\a'
          fi
        }

        builtin typeset -ag precmd_functions preexec_functions
        preexec_functions+=(_ourocode_preexec)
        precmd_functions=(${precmd_functions:/_ourocode_deferred_init/_ourocode_precmd})
        builtin autoload -Uz add-zle-hook-widget
        add-zle-hook-widget line-init _ourocode_zle_line_init
        _ourocode_precmd
        builtin unfunction _ourocode_deferred_init
      }

      # Register early, initialize late. This lets `.zshrc` and prompt themes
      # finish configuring hook arrays before Ourocode touches them.
      builtin typeset -ag precmd_functions
      precmd_functions+=(_ourocode_deferred_init)
    fi
    """#

    private static func writeIfChanged(_ data: Data, to url: URL) throws {
        if let existing = try? Data(contentsOf: url), existing == data { return }
        try data.write(to: url, options: .atomic)
    }
}
